modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="horror_mod_control"
version="1.0.0"
displayName="HorrorModControl"
displayURL="https://mcreator.net"
credits="Created using MCreator"
authors="Lukenni"
description="Made for this modpack"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.horror_mod_control]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.horror_mod_control]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration